#ifndef H_ERRORS_H
#define H_ERRORS_H

typedef enum error {
	INPUT_FILE_FAILED_TO_OPEN = 1,
	INPUT_FILE_FAILED_TO_CLOSE,
	INVALID_CHARACTER_ENCOUNTERED,
	INSUFFICIENT_COMMAND_LINE_ARGUMENTS,
}error;

#endif
