#ifndef H_ERRORS_H
#define H_ERRORS_H

typedef enum error {
	INVALID_COMMAND_INPUT = 1,
	INPUT_FILE_FAILED_TO_OPEN,
	INPUT_FILE_FAILED_TO_CLOSE,
	INVALID_CHARACTER_ENCOUNTERED,
	INSUFFICIENT_COMMAND_LINE_ARGUMENTS,
	ROBOT_UNABLE_TO_REACH_END_OF_MAZE,
}error;

#endif
